updated affiliations
iSPIRT/pushpaka pull request #15
Opened 2021-11-28 11:38 UTC by flyamigo

2021-12-07 14:56 UTC, hrishiballal requested changes

2021-12-07 14:56 UTC, hrishiballal commented on docs/index.md
> +| Hrishikesh Ballal    | <a href="https://about.openskies.sh/#contact" target="_blank"><i class="fa fa-link"></i></a> |      | iSpirt                           | 🇮🇪     |
Thank you for this, I am not a part of iSpirt, I am representing as Aerobridge.

2021-12-09 15:43 UTC, sayandeep-ai commented on docs/index.md
> +| Sayandeep Purkayasth | [<i class="fa fa-envelope-o"></i>](mailto:sayandeep@deepcyan.ai)                             |      | iSpirt                           | 🇮🇳     |
I'm comfortable having both: iSpirt & Deepcyan.

2021-12-09 15:45 UTC, sayandeep-ai commented on docs/index.md
> +| Sayandeep Purkayasth | [<i class="fa fa-envelope-o"></i>](mailto:sayandeep@deepcyan.ai)                             |      | iSpirt                           | 🇮🇳     |
In fact, we should advertise that we have varied membership, so the whole workstream doesn't get categorised as biased or opinionated.

2022-01-07 17:53 UTC, closed without merging